---
title: "Restionaceae"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(spectrolab)
library(tidyverse)
library(readr)
library(readxl)
library(stringr)
library(picante)
library(phytools)
```



```{r}
# Get phylogeny
# Proteaceae # tree <- read.nexus("/home/jasper/Dropbox/SAEON/Projects/ProteaAtlas/OnsteinTree/MCC Proteaceae Onstein et al")

tree <- read.tree("/home/jasper/Dropbox/SAEON/Projects/Restionaceae/Linder2019/RestionoideaeBayesian1000posttrees.txt")

plot(tree[[1000]], cex = 0.2, type = "fan")
```

```{r}
# Get spectra, filter and reformat to class spectra
dat <- read_csv("/home/jasper/GIT/ZA_Dimensions_Data/data_base/full_spectra_trait_conjoined.csv")
dat <- dat %>% filter(family == "RESTIONACEAE") 
colnames(dat)[58:557] <- 450:949
#spec <- as_spectra(dat, name_idx = 2, meta_idxs = c(1, 3:57))

```

```{r}
spp <- unique(dat$SpeciesID)
spp <- gsub(" ", "_", spp)
keeps <- spp[which(spp %in% tree[[1000]]$tip.label)]
nokeeps <- spp[-which(spp %in% tree[[1000]]$tip.label)]

stree <- keep.tip(phy = tree[[1000]], tip = spp)
```


```{r}
#phylosig(tree, x, method="K", test=T, nsim=1000)
```

